### ISSUE TITLE
Group creation

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#10]
Creating new group shows "Done" on the button (should say next?)

![image](https://user-images.githubusercontent.com/814886/79270364-443a0c00-7e5b-11ea-972a-511cb3f26e7c.png)

**Comment by Evanfeenstra** [comment]
in ios app it also says "Done", as this is the last step in the process

**Comment by pitoi** [comment]
Looking back at the chat, I didn't describe the issue properly. It looks like the problem was the spinner next to the done button was running indefinitely.

**Comment by Evanfeenstra** [comment]
Im not able to reproduce this one...
