### ISSUE TITLE
going to a specific user chat get me stuck on a white screen

### ISSUE THREAD

**Issue by Transisto** [stakwork/sphinx-android#104]
Last I remember the user in question was on OSX and shared a jitsy call link.

**Comment by Transisto** [comment]
Since then every messages was deleted and I still get sent to a white screen, 
I do get to see all the messages for about half a second right before the "whiteout"

**Comment by pitoi** [comment]
If force quit, then restart doesn't help, you could try saving the contact pubkey then delete and re-add them. As a last resort, you could export your keys, then reinstall the APK and paste in your key string to restore.

**Comment by Transisto** [comment]
Thanks it worked, just deleted the contact and that person send me back another message.
