### ISSUE TITLE
Layout issue on msg

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#11]
The margin between the keyboard and textfield for entering a msg is small.
Seen here on a Xiaomi mix 2. Also seeing it on my motorola.

![2020-04-14 14 25 14](https://user-images.githubusercontent.com/814886/79270840-14d7cf00-7e5c-11ea-8dc1-2747906d4c2a.jpg)

**Comment by Evanfeenstra** [comment]
fixed in latest APK, please confirm

**Comment by pitoi** [comment]
fixed for me, might pop up on a different phone model.
