### ISSUE TITLE
Layout issue on text string with image attachment

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#12]
Bottom of text note on attachment is getting cropped.

![image](https://user-images.githubusercontent.com/814886/79270977-4bade500-7e5c-11ea-80cd-58234d3a5068.png)

**Comment by pitoi** [comment]
similar issue is happening with paid attachments

![Screenshot_2020-04-14-18-15-01-639_com sphinx](https://user-images.githubusercontent.com/814886/79278748-9b46dd80-7e69-11ea-8c29-40e344a217ff.png)

**Comment by Evanfeenstra** [comment]
fixed in latest APK

**Comment by bitcoinuser** [comment]
Please close the bugs that was already fixed. Thanks.
