### ISSUE TITLE
~1/2 of Android apps are now instantly crashing since failed setup. Phone semi-bricked

### ISSUE THREAD

**Issue by champbronc2** [stakwork/sphinx-android#134]
Using a Galaxy S10e, Android version 11, One UI Version 3.0

So earlier today I was on the final step of setting up my Sphinx account; I uploaded a profile picture, then hit "Finish Setup"

The spinner went on for several minutes, so I closed the app.

Then after trying to open the app, it would instantly crash. So I tried uninstalling, and reinstalling the app. Tried deleting cache + resetting app preferences.

Examples of some various apps that instantly crash now:
- ESPN
- Investing.com
- Email
- Google Search as soon as anything is typed into the search bar (Chrome is fine however)

Sphinx also crashes as soon as I open it.

Hoping I don't need to factory reset..

**Comment by pitoi** [comment]
Can you recall if anything else changed on your phone? I don't think an android app can cause other apps to crash. Maybe delete sphinx and try to use the phone without it and see.

**Comment by champbronc2** [comment]
Yup, in that state currently and apps still crash immediately.

Nothing else changed on my phone today, this all started a few hours ago directly after being unable to complete Sphinx setup. 

If it helps find more info, my invite code ended in fb356d5

**Comment by Evanfeenstra** [comment]
One app cannot cause another app to crash, you probably just ran out storage space on your phone

**Comment by champbronc2** [comment]
So put the other apps aside, what happened to my invite? The invite code no longer works, but I also can't login to my account. Do I need a new invite?

Will keep digging on the other apps, and make some addtl space

**Comment by pitoi** [comment]
Keep us posted on the crashing, in case it comes up on the next install. You can email support@stakwork.com and link to this thread and we will email you a new invite. When you log in, go to the main menu > profile > export keys. This string will allow you to sync devices and restore if you delete the app.

**Comment by champbronc2** [comment]
Sent an email, thanks for the help all!

I think it was coincidence that the bug happened ~installation, as it seems this bug is more widespread https://www.androidauthority.com/android-apps-crashing-1210994/

I've been able to fix each crashing app by deleting the app data.

Hopefully round 2 works better :)
