### ISSUE TITLE
Missing `android/app/build.copy.gradle` file

### ISSUE THREAD

**Issue by CypherPoet** [stakwork/sphinx-android#137]
The steps for contributing mention:

> 3. Rename `android/app/build.copy.gradle` to `android/app/build.gradle`

However, the latest such file I could find was [here](https://github.com/stakwork/sphinx-android/blob/df7588490d351e39dbe68845c51e338661bd1cdd/android/app/build.copy.gradle). The current project doesn't seem to have it and running `npm run android` fails with:

```sh
FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.
```

I'll try to reuse the old file when I get the chance and see how that works.

**Comment by Evanfeenstra** [comment]
sorry, I've updated the file https://github.com/stakwork/sphinx-android/blob/master/android/app/build.copy.gradle

**Comment by CypherPoet** [comment]
@Evanfeenstra Thanks -- that fixes the task error. 

It I think this might have been caused by renaming the file instead of copying it at some point -- and then the .gitignore causes it to never get pushed back up.
