### ISSUE TITLE
Long message overflow on dashboard

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#14]
When a message exceeds the allowed char count, we should end in an ellipse (...)

![image](https://user-images.githubusercontent.com/814886/79278799-b580bb80-7e69-11ea-8b24-ba1adc91bc23.png)

**Comment by Evanfeenstra** [comment]
fixed in latest APK

**Comment by bitcoinuser** [comment]
Please close the bugs that was already fixed. Thanks.
