### ISSUE TITLE
Missing `google-services.json` file causes error during `npm run android`

### ISSUE THREAD

**Issue by CypherPoet** [stakwork/sphinx-android#140]
After installing dependencies and getting my local `build.gradle` file set up, running `npm run android` fails with the following error: 

```sh
> Task :app:processDebugGoogleServices FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
125 actionable tasks: 2 executed, 123 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
```

[Some digging](https://stackoverflow.com/questions/33866061/error-file-google-services-json-is-missing-from-module-root-folder-the-google/50173745) seems to suggest that this is related to the app's [Firebase setup](https://firebase.google.com/docs/android/setup), but I'm not sure I have the right permissions/credentials to address this.

(cc @pitoi @Evanfeenstra)

**Comment by Evanfeenstra** [comment]
@CypherPoet do you have an email i can send the google services file to

**Comment by CypherPoet** [comment]
Everything seems to be building just fine now after getting this in place. Thanks again, @Evanfeenstra
