### ISSUE TITLE
I sent an image and on main window appear as Picture Received

### ISSUE THREAD

**Issue by bitcoinuser** [stakwork/sphinx-android#18]
I sent an image and on main window appear as Picture Received. Should be Picture Sent.

![photo_2020-04-15_10-33-42](https://user-images.githubusercontent.com/1178856/79343414-bfa3c800-7f04-11ea-8c99-19ad2d20a54e.jpg)

**Comment by Evanfeenstra** [comment]
fixed in latest APK
