### ISSUE TITLE
Update balance for external invoices

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#2]
When paying to a non-sphinx pubkey, the balance doesn't update.
Recreate:
 - note the wallet balance on the dashboard
 - create an invoice for a service like lightningspin.com and note the amount
 - pay it using the QR code reader on the dashboard
 - check the transaction list to see if it succeeded
 - check the balance on the dashboard
 - restart and check balance

**Comment by Evanfeenstra** [comment]
fixed in latest APK

**Comment by bitcoinuser** [comment]
Please close the bugs that was already fixed. Thanks.
