### ISSUE TITLE
I see checkmark on sent messages but the other user didn't not received the messages

### ISSUE THREAD

**Issue by bitcoinuser** [stakwork/sphinx-android#25]
I see checkmark on sent messages but the other user didn't not received the messages. 
Obs. The messages appeared on the other user after many seconds and after other new messages.
So there was a lag to receive some messages even with checkmark on the sphinx app of the user who sent the message.

**Comment by Evanfeenstra** [comment]
note: we will use https://github.com/pladaria/reconnecting-websocket to make sure socket is always ready to receive new messages

**Comment by Evanfeenstra** [comment]
ok the websocket connection has been updated, let us know if this problem persists

**Comment by bitcoinuser** [comment]
Closing. If I reproduce again I reopen.
