### ISSUE TITLE
Layout on invoice

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#3]
The layout breaks when the memo field is selected and the keyboard is expanded.
Recreate:
 - tap create invoice (arrow on bottom right) on the dashboard
 - tap the memo field
 - I'm able to close the window using the red x, but another user reported not being able to tap the x. 

![Screenshot_20200414-081522](https://user-images.githubusercontent.com/814886/79235188-8433cb80-7e28-11ea-80a2-43cbde52ebc3.png)

![image](https://user-images.githubusercontent.com/814886/79235208-8d249d00-7e28-11ea-95ca-3a5811511349.png)

**Comment by bitcoinuser** [comment]
Fixed too.

**Comment by bitcoinuser** [comment]
Please close this as it was fixed. Thanks.

**Comment by pitoi** [comment]
verified
