### ISSUE TITLE
No error and no payment 

### ISSUE THREAD

**Issue by bitcoinuser** [stakwork/sphinx-android#4]
Sometimes when I try to pay an external invoice, after I click confirm, no payment is done and no error message appear. The window just close.

**Comment by Evanfeenstra** [comment]
Please post an example invoice string @bitcoinuser . Also, have you downloaded the latest APK from sphinx.chat?

**Comment by bitcoinuser** [comment]
If I reproduce this again, I reopen the bug. I think the invoice I tried was from Breez wallet.
