### ISSUE TITLE
When I click send, the message appear for me but not for the contact I sent the message

### ISSUE THREAD

**Issue by bitcoinuser** [stakwork/sphinx-android#42]
When I click send, the message appear for me but not for the contact I sent the message.
I reproduce this problem many times. For example: I send like 5 messages, but the person only see 3 messages.

**Comment by bitcoinuser** [comment]
It's impossible to use sphinx with this problem. Hope the problem be fixed soon.

**Comment by Evanfeenstra** [comment]
@bitcoinuser are you on a hosted node, or a home node?

**Comment by bitcoinuser** [comment]
Hosted

**Comment by bitcoinuser** [comment]
I think this bug is fixed. If I reproduce this again, I reopen it.
