### ISSUE TITLE
Add friend button inactive/grey

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#44]
Samsung S9
has 15k sats locally
When tapping Add Friend -> New to Sphinx, the button is greyed out and can't be tapped even though field values look ok.

![image](https://user-images.githubusercontent.com/814886/81506503-f8408280-92b3-11ea-9dd8-fab200b0e604.png)

**Comment by charrocket** [comment]
latest update finally allow to generate invitation codes.
