### ISSUE TITLE
Android back button on chat window minimize Sphinx

### ISSUE THREAD

**Issue by bitcoinuser** [stakwork/sphinx-android#5]
When I'm on chat window and I click on Android back button, instead of go to Sphinx main window, it minimize Sphinx. I reproduce this on Xiaomi phones. 
On older Sphinx versions this was working ok. So I think this is a regression.

**Comment by bitcoinuser** [comment]
Same problem on scan qrcode window.

**Comment by Evanfeenstra** [comment]
download the new APK

**Comment by bitcoinuser** [comment]
Fixed, thanks.
