### ISSUE TITLE
Images full screen view

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-android#51]
It looks like the zoom factor on android is causing images to be too large. Also, the user can't pinch to resize or rotate to view. This image compares the original image with the android on the right.

![IMG_20200605_125017415_HDR](https://user-images.githubusercontent.com/814886/83912986-0905dc00-a72c-11ea-81b7-d2855780b20d.jpg)

**Comment by charrocket** [comment]
version from 5 of june fixes this for me, for payed images and non payed.

**Comment by charrocket** [comment]
june 5 version fixes this for me, for payed images and non payed.
