### ISSUE TITLE
The last message on chat window is hidden if I click on message field to show keyboard 

### ISSUE THREAD

**Issue by bitcoinuser** [stakwork/sphinx-android#6]
The last message on chat window is hidden if I click on message field to show keyboard

**Comment by Evanfeenstra** [comment]
thanks for posting the issue, try out the new APK

**Comment by bitcoinuser** [comment]
Fixed, thanks.

**Comment by bitcoinuser** [comment]
A new problem was introduced. Now on a chat with for example only two messages, when clicking on message field, the two messages disappear.

**Comment by bitcoinuser** [comment]
Reopen as the problem is back on the new version.
